<template>
    <div>
        <div class="grid grid-cols-12 mt-8">
            <div class="col-span-12 lg:col-span-8 sm:col-span-12">
                <h2 class="text-lg font-medium truncate mr-5">
                    Category Create
                </h2>
            </div>
        </div>
        <div class="grid grid-cols-12 gap-6 mt-5">
            <div class="intro-y col-span-12 lg:col-span-8">
                <div class="w-full intro-y box p-5">
                    <div class="flex flex-wrap -mx-3 mb-6">
                        <div class="w-full md:w-1/4 px-3 mb-4">
                            <label class="form-label"
                                   for="name">
                                Name
                            </label>
                            <div class="flex items-center">
                                <input
                                    class="form-control w-full"
                                    id="name" placeholder="Enter Name" type="text"
                                    v-model="data.name">
                            </div>
                        </div>

                        <div class="w-full md:w-1/4 px-3 mb-4">
                            <label class="form-label"
                                   for="slug">
                                Slug
                            </label>
                            <div class="flex items-center">
                                <input
                                    class="form-control w-full"
                                    id="slug" placeholder="Slug is autogenerated" type="text"
                                    readonly
                                    v-model="slug">
                            </div>
                        </div>

                        <div class="w-full px-3 mb-4">
                            <label class="form-label"
                                   for="icon">
                                Browse Icon
                            </label>
                            <FileUpload
                                id="icon"
                                accept_file_types="image/jpeg, image/png, image/svg+xml"
                                label="Browse"
                                max_file_size="1MB"
                                @process="setImage($event,'icon')"
                            />
                        </div>
                    </div>
                </div>

                <div class="w-full intro-y box mt-4 p-5">
                    <div class="flex flex-wrap -mx-3 mb-6">
                        <div class="w-full px-3 mb-4">
                            <label class="form-label"
                                   for="meta_title">
                                Meta Title
                            </label>
                            <div class="flex items-center">
                                <input
                                    class="form-control w-full"
                                    id="meta_title" placeholder="Enter Meta Title" type="text"
                                    v-model="data.meta_title">
                            </div>
                        </div>

                        <div class="w-full px-3 mb-4">
                            <label class="form-label"
                                   for="meta_keyword">
                                Meta Keyword
                            </label>
                            <div class="flex items-center">
                                <input
                                    class="form-control w-full"
                                    id="meta_keyword" placeholder="Enter Meta Keyword" type="text"
                                    v-model="data.meta_keywords">
                            </div>
                        </div>

                        <div class="w-full px-3 mb-4">
                            <label class="form-label"
                                   for="meta_description">
                                Meta Description
                            </label>
                            <div class="flex items-center">
                                <textarea
                                    id="meta_description" class="form-control w-full"
                                    v-model="data.meta_description"
                                    cols="30" rows="10"
                                ></textarea>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="text-right mt-5">
                    <a href="/market/category"
                       class="btn btn-outline-secondary w-24 mr-1">Cancel</a>
                    <button type="submit"
                            class="btn btn-primary w-24"
                            :disabled="btnLoading"
                            @click="onSubmit">Save
                    </button>
                </div>
            </div>

            <div class="intro-y col-span-12 lg:col-span-4">
                <div class="w-full intro-y box p-5">
                    <div class="flex flex-wrap -mx-3 mb-6">

                        <div class="w-full px-3 mb-4">
                            <label class="form-label"
                                   for="is_active">
                                Active Status
                            </label>
                            <div class="form-switch mt-2">
                                <input type="checkbox"
                                       id="is_active"
                                       class="form-check-input"
                                       :checked="data.is_active"
                                       @change="onCheckbox($event,'is_active')"/>
                            </div>
                        </div>

                        <div class="w-full px-3 mb-4">
                            <label class="form-label"
                                   for="featured_for_home">
                                Featured For Home
                            </label>
                            <div class="form-switch mt-2">
                                <input type="checkbox"
                                       id="featured_for_home"
                                       class="form-check-input"
                                       :checked="data.featured_for_home"
                                       @change="onCheckbox($event,'featured_for_home')"/>
                            </div>
                            <small>The product will be added in Home</small>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</template>

<script>
import FileUpload from '../FileUpload'

export default {
    name: "Add",
    components: {
        FileUpload,
    },
    data: function () {
        return {
            data: {
                name: "",
                icon: "",
                meta_title: null,
                meta_keywords: null,
                meta_description: null,
                is_active: true,
                featured_for_home: true,
            },
            btnLoading: false
        }
    },
    computed: {
        slug: function () {
            return this.sanitizeTitle(this.data.name);
        }
    },
    methods: {
        sanitizeTitle: function (title) {
            if (!title) {
                return "";
            }
            let slug = "";
            // Change to lower case
            const titleLower = title.toLowerCase();
            // Letter "e"
            slug = titleLower.replace(/e|é|è|ẽ|ẻ|ẹ|ê|ế|ề|ễ|ể|ệ/gi, 'e');
            // Letter "a"
            slug = slug.replace(/a|á|à|ã|ả|ạ|ă|ắ|ằ|ẵ|ẳ|ặ|â|ấ|ầ|ẫ|ẩ|ậ/gi, 'a');
            // Letter "o"
            slug = slug.replace(/o|ó|ò|õ|ỏ|ọ|ô|ố|ồ|ỗ|ổ|ộ|ơ|ớ|ờ|ỡ|ở|ợ/gi, 'o');
            // Letter "u"
            slug = slug.replace(/u|ú|ù|ũ|ủ|ụ|ư|ứ|ừ|ữ|ử|ự/gi, 'u');
            // Letter "d"
            slug = slug.replace(/đ/gi, 'd');
            // Trim the last whitespace
            slug = slug.replace(/\s*$/g, '');
            // Change whitespace to "-"
            slug = slug.replace(/\s+/g, '-');

            return slug;
        },
        setImage(img, key, index = null) {
            if (index == null) {
                this.data[key] = img
            } else {
                this.data.items[index][key] = img;
            }
        },
        onSubmit() {
            this.btnLoading = true;
            axios.post('/market/category', this.data)
                .then(() => {
                    this.btnLoading = false;
                    this.$alertify.success('Category created successfully')

                    setTimeout(() => {
                        window.location.href = '/market/category'
                    }, 1000);

                }).catch((error) => {
                this.btnLoading = false;
                if (error.response.status === 422) {
                    this.$alertify.error(Object.values(error.response.data.errors)[0][0])
                }
            })
        },
        onCheckbox(e, key) {
            this.data[key] = e.target.checked;
        }
    }
}
</script>

<style scoped>
@media (min-width: 768px) {
    .md\:w-1\/2 {
        width: 25%;
    }

    .md\:w-1\/3 {
        width: 33.333333%;
    }

    .md\:w-1\/4 {
        width: 50%;
    }

    .md\:w-1\/5 {
        width: 75%;
    }
}

.border-radius-15 {
    border-radius: 15px;
}

.close {
    position: absolute;
    right: 12px;
    margin-top: -10px;
}
</style>
