<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Str;

class Blog extends Model
{
    use HasFactory;

    public const UPLOADS = [
        'image'
    ];

    protected $table = 'tbl_blogs';

    protected $appends = [
        'image_link'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(static function ($data) {
            $data->slug = Str::slug($data->title);
        });

        static::updating(static function ($data) {
            $data->slug = Str::slug($data->title);
        });
    }

    public function getImageLinkAttribute(): string
    {
        return $this->getImagePath('image');
    }

    public function stores(): BelongsToMany
    {
        return $this->belongsToMany(Store::class, 'blog_store');
    }

    public function blog_category(): BelongsTo
    {
        return $this->belongsTo(BlogCategory::class);
    }
}
