<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasEvents;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class Category extends Model
{
    use HasFactory;

    public const UPLOADS = [
        'icon'
    ];

    protected $table = 'tbl_categories';

    protected $appends = [
        'icon_link'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(static function ($data) {
            $data->slug = Str::slug($data->name);
        });
    }

    public function getIconLinkAttribute(): string
    {
        return $this->getImagePath('icon');
    }

    public function stores(): HasMany
    {
        return $this->hasMany(Store::class)->latest();
    }
}
