<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class Store extends Model
{
    use HasFactory;

    public const UPLOADS = [
        'image'
    ];

    protected $table = 'tbl_stores';

    protected $appends = [
        'image_link'
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(static function ($data) {
            $data->slug = Str::slug($data->name);
        });
    }

    public function getImageLinkAttribute(): string
    {
        return $this->getImagePath('image');
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    public function coupons(): HasMany
    {
        return $this->hasMany(Coupon::class)
            ->orderBy('sort_by');
    }

}
